<?php

return [
    'cratureSize' => [
        '1' => 'Tiny',
        '2' => 'Small',
        '3' => 'Medium',
        '4' => 'Large',
        '5' => 'Huge',
        '6' => 'Gargantuan',
    ],
    'spellLevel' => [
        '0' => 'Cantrip',
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
        '6' => '6',
        '7' => '7',
        '8' => '8',
        '9' => '9'
    ],
    'castingTime' => [
        '1' => '1 Reaction',
        '2' => '1 Bonus Action',
        '3' => '1 Action',
        '4' => '1 Minute',
    ],
    'areaOfEffect' => [
        "0" => 'Self',
        "1" => 'Touch',
        "2" => 'Spot',
        "3" => 'Cone',
        "4" => 'Cube',
        "5" => 'Line',
        "6" => 'Sphere',
    ],
    'duration' => [
        '0' => 'Instantaneous',
        '10' => '1 round',
        '20' => '1 minute',
        '21' => '1 minute - Consentrate',
        '30' => '10 minutes',
        '31' => '10 minutes - Consentrate',
        '40' => '1 hour',
        '41' => '1 hour - Consentrate',
        '50' => '8 hours',
        '51' => '8 hours - Consentrate',
        '90' => 'Until despelled',
    ],
    'challenge' => [
        '1/8' => 25, 
        '1/4' => 50, 
        '1/2' => 100, 
        '1' => 200, 
        '2' => 450, 
        '3' => 700, 
        '4' => 1100, 
        '8' => 3900, 
    ],
    'alignment' => [
        "1" => 'Chaotic Evil',
        "2" => 'Natural Evil',
        "3" => 'Lawfull Evil',
        "4" => 'Chaotic Natural',
        "5" => 'True Natural',
        "6" => 'Lawfull Natural',
        "7" => 'Chaotic Good',
        "8" => 'Natural Good',
        "9" => 'Lawfull Good',
    ],
    'cratureType' => [
        "1" => 'Aberration',
        "2" => 'Beast',
        "3" => 'Dragon',
        "4" => 'Giant',
        "5" => 'Humanoid',
        "6" => 'Monstrosity',
        "7" => 'Ooze',
        "8" => 'Plant',
        "9" => 'Undead',
    ],
];