<?php

return [
    'cratureSize' => [
        '1' => 'Tiny',
        '2' => 'Small',
        '3' => 'Medium',
        '4' => 'Large',
        '5' => 'Huge',
        '6' => 'Gargantuan',
    ],
    'spellLevel' => [
        '0' => 'Cantrip',
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '5' => '5',
        '6' => '6',
        '7' => '7',
        '8' => '8',
        '9' => '9'
    ],
    'castingTime' => [
        '1' => '1 Reaction',
        '2' => '1 Bonus Action',
        '3' => '1 Action',
        '4' => '1 Minute',
    ],
    'areaOfEffect' => [
        "0" => 'Self',
        "1" => 'Touch',
        "2" => 'Spot',
        "3" => 'Cone',
        "4" => 'Cube',
        "5" => 'Line',
        "6" => 'Sphere',
    ],
    'duration' => [
        '0' => 'Instantaneous',
        '10' => '1 round',
        '20' => '1 minute',
        '21' => '1 minute - Consentrate',
        '30' => '10 minutes',
        '31' => '10 minutes - Consentrate',
        '40' => '1 hour',
        '41' => '1 hour - Consentrate',
        '50' => '8 hours',
        '51' => '8 hours - Consentrate',
        '90' => 'Until despelled',
    ],
    'cratureType' => [
        "10" => 'Aberration',
        "20" => 'Beast',
        "30" => 'Dragon',
        "40" => 'Giant',
        "50" => 'Humanoid',
        "51" => 'Humanoid (Goblonoid)',
        "60" => 'Monstrosity',
        "70" => 'Ooze',
        "80" => 'Plant',
        "90" => 'Undead',
    ],
];